version: '3'
services:
  registration:
    build:
      context: ../.
      dockerfile: Dockerfile.prd
    image: jaderdomonte/registration
    container_name: registration
    entrypoint: dockerize -wait tcp://db-registration:5432 java -cp app:app/lib/* com.montesan.university.registration.UniversityRegistrationApplication
    ports:
      - 8001:8080
    depends_on:
      - db-registration

  db-registration:
    image: postgres:13.1
    #container_name: db-registration
    environment:
      - POSTGRES_PASSWORD=registration
      - POSTGRES_DB=registration
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d

networks:
  default:
    external:
      name: university-network
