version: '3'
services:
  registration:
    build: 
      context: ../.
      dockerfile: Dockerfile.prd
    image: jaderdomonte/registration
    container_name: registration
    entrypoint: dockerize -wait tcp://postgres:5432 java -cp app:app/lib/* com.montesan.university.registration.UniversityRegistrationApplication
    ports:
      - 9000:8080
    depends_on:
      - postgres

  postgres:
    image: postgres:13.1
    container_name: postgres
    environment:
      - POSTGRES_PASSWORD=registration
      - POSTGRES_DB=registration
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432

networks:
  default:
    external:
      name: university-network
