version: '3'
services:
  db-academic:
    image: postgres:13.1
    container_name: db-academic
    environment:
      - POSTGRES_PASSWORD=academic
      - POSTGRES_DB=academic
    ports:
      - 5432:5432
    volumes:
      - ../postgres/init:/docker-entrypoint-initdb.d

networks:
  default:
    external:
      name: university-network
